main: ${mainClass.get()}
name: ${pluginName}
author: Deltik
website: https://github.com/Deltik/SignEdit
version: "${pluginVersion}"
api-version: "1.13"
description: Edit existing signs
commands:
  sign:
    aliases: [signedit, editsign, se]
    description: Edit a targeted sign
    usage: |
      See the online documentation for additional help:
      https://git.io/SignEdit-README

      /<command> help [<page>]
        Show usage syntax for every available /<command> subcommand.
        Specify a <page> number to view a specific page.

      /<command> ui
        Open the native Minecraft sign editor on the targeted sign.

      /<command> [set] <lines> [<text>]
        Change each of the lines <lines> of the targeted sign to <text>.
        Formatting codes are parsed with `&` in place of `ยง`.
        If <text> is blank, erase the lines <lines>.
        "set" can be omitted.

      /<command> clear [<lines>]
        Erase the text on the targeted sign.
        If <lines> is specified, only those lines are blanked out.

      /<command> cancel
        Abort your pending sign edit action.

      /<command> status
        Show the pending action, what is in the copy buffer, and an overview of the undo/redo history stack.

      /<command> copy [<lines>]
        Copy the targeted sign's text.
        If <lines> is specified, only those lines are copied.

      /<command> cut [<lines>]
        Copy the targeted sign's text and remove it from the sign.
        If <lines> is specified, only those lines are cut.

      /<command> paste
        Paste the lines buffered by the previous /sign copy or /sign cut command onto the targeted sign.

      /<command> undo
        Revert the previous sign change.

      /<command> redo
        Restore the most recent sign change that was undone by /sign undo.

      /<command> unwax
        Remove the honeycomb wax from the sign, allowing it to be edited again.

      /<command> wax
        Apply honeycomb wax to the sign, preventing it from being edited again.

      /<command> version
        Show the version of this plugin.

permissions:
  signedit.use:
    description: Legacy permission granting access to all /sign subcommands
  signedit.sign.*:
    description: Allow access to all /sign subcommands
    children:
      signedit.sign.help: true
      signedit.sign.ui: true
      signedit.sign.set: true
      signedit.sign.clear: true
      signedit.sign.cancel: true
      signedit.sign.status: true
      signedit.sign.copy: true
      signedit.sign.cut: true
      signedit.sign.paste: true
      signedit.sign.undo: true
      signedit.sign.redo: true
      signedit.sign.unwax: true
      signedit.sign.wax: true
      signedit.sign.version: true
  signedit.sign.help:
    description: Allow /sign help
  signedit.sign.ui:
    description: Allow /sign ui
  signedit.sign.set:
    description: Allow /sign set
  signedit.sign.clear:
    description: Allow /sign clear
  signedit.sign.cancel:
    description: Allow /sign cancel
  signedit.sign.status:
    description: Allow /sign status
  signedit.sign.copy:
    description: Allow /sign copy
  signedit.sign.cut:
    description: Allow /sign cut
  signedit.sign.paste:
    description: Allow /sign paste
  signedit.sign.undo:
    description: Allow /sign undo
  signedit.sign.redo:
    description: Allow /sign redo
  signedit.sign.unwax:
    description: Allow /sign unwax; access to this command implicitly removes wax when editing with another command
  signedit.sign.wax:
    description: Allow /sign wax; access to this command implicitly reapplies wax if the sign was previously waxed
  signedit.sign.version:
    description: Allow /sign version