main: ${mainClassName}
name: ${pluginName}
author: Deltik
website: https://github.com/Deltik/SignEdit
version: "${pluginVersion}"
api-version: "1.13"
description: Edit existing signs
commands:
  sign:
    aliases: [signedit, editsign, se]
    description: Edit a targeted sign
    usage: |
      See the online documentation for detailed usage help:
      https://git.io/SignEdit-README

      /<command> ui
        Invoke the native Minecraft sign editor on the targeted sign.

      /<command> set <lines> [<text>]
        Change each of the lines <lines> of the targeted sign to <text>.
        Formatting codes are parsed with `&` in place of `ยง`.
        If <text> is blank, erase the lines <lines>.

      /<command> <lines> [<text>]
        Alias of /<command> set <lines> [<text>]

      /<command> clear [<lines>]
        Erase the lines <lines> of the targeted sign.

      /<command> <lines>
        Alias of /<command> clear <lines>

      /<command> cancel
        Abort your pending right-click action.

      /<command> status
        Show the pending action, what is in the copy buffer, and an overview of the undo/redo history stack.

      /<command> copy [<lines>]
        Copy the targeted sign's text.
        If <lines> is specified, only those lines are copied.

      /<command> cut [<lines>]
        Copy the targeted sign's text and remove it from the sign.
        If <lines> is specified, only those lines are cut.

      /<command> paste
        Paste the lines buffered by the previous /sign copy or /sign cut command onto the targeted sign.

      /<command> undo
        Revert the previous sign change.

      /<command> redo
        Restore the most recent sign change that was undone by /sign undo.

      /<command> version
        Show the version of this plugin.

permissions:
  SignEdit.use:
    description: Legacy permission granting access to all commands in this plugin
  signedit.sign.*:
    description: Allow access to all /sign subcommands
    children:
      signedit.sign.ui: true
      signedit.sign.set: true
      signedit.sign.clear: true
      signedit.sign.cancel: true
      signedit.sign.status: true
      signedit.sign.copy: true
      signedit.sign.cut: true
      signedit.sign.paste: true
      signedit.sign.undo: true
      signedit.sign.redo: true
      signedit.sign.version: true
  signedit.sign.ui:
    description: Allow /sign ui
  signedit.sign.set:
    description: Allow /sign set
  signedit.sign.clear:
    description: Allow /sign clear
  signedit.sign.cancel:
    description: Allow /sign cancel
  signedit.sign.status:
    description: Allow /sign status
  signedit.sign.copy:
    description: Allow /sign copy
  signedit.sign.cut:
    description: Allow /sign cut
  signedit.sign.paste:
    description: Allow /sign paste
  signedit.sign.undo:
    description: Allow /sign undo
  signedit.sign.redo:
    description: Allow /sign redo
  signedit.sign.version:
    description: Allow /sign version