/*
 * Copyright (C) 2017-2025 Deltik <https://www.deltik.net/>
 *
 * This file is part of SignEdit for Bukkit.
 *
 * SignEdit for Bukkit is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SignEdit for Bukkit is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SignEdit for Bukkit.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.deltik.mc.signedit.subcommands;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;

/**
 * Annotation processor that generates {@link GeneratedSubcommandClasses} at compile time.
 * This discovers all classes annotated with {@link SignSubcommandInfo} and generates
 * a registry class with metadata about each subcommand.
 */
@SupportedAnnotationTypes("net.deltik.mc.signedit.subcommands.SignSubcommandInfo")
@SupportedSourceVersion(SourceVersion.RELEASE_8)
public class SignSubcommandProcessor extends AbstractProcessor {
    private boolean generated = false;

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (generated) {
            return false;
        }

        List<SubcommandEntry> entries = new ArrayList<>();

        for (Element element : roundEnv.getElementsAnnotatedWith(SignSubcommandInfo.class)) {
            if (!(element instanceof TypeElement)) {
                continue;
            }

            TypeElement typeElement = (TypeElement) element;
            SignSubcommandInfo info = element.getAnnotation(SignSubcommandInfo.class);

            entries.add(new SubcommandEntry(
                    info.name(),
                    typeElement.getQualifiedName().toString(),
                    typeElement.getSimpleName().toString(),
                    info.supportsLineSelector()
            ));
        }

        if (entries.isEmpty()) {
            return false;
        }

        // Sort by name for consistent ordering
        entries.sort(Comparator.comparing(e -> e.name));

        try {
            generateClass(entries);
            generated = true;
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                    javax.tools.Diagnostic.Kind.ERROR,
                    "Failed to generate GeneratedSubcommandClasses: " + e.getMessage()
            );
        }

        return true;
    }

    private void generateClass(List<SubcommandEntry> entries) throws IOException {
        JavaFileObject file = processingEnv.getFiler().createSourceFile(
                "net.deltik.mc.signedit.subcommands.GeneratedSubcommandClasses"
        );

        try (PrintWriter out = new PrintWriter(file.openWriter())) {
            out.println("/*");
            out.println(" * AUTO-GENERATED FILE - DO NOT EDIT");
            out.println(" * Generated by SignSubcommandProcessor");
            out.println(" */");
            out.println();
            out.println("package net.deltik.mc.signedit.subcommands;");
            out.println();
            out.println("import java.util.*;");
            out.println();
            out.println("/**");
            out.println(" * Auto-generated class containing metadata about all SignEdit subcommands.");
            out.println(" * Generated at compile time by {@link SignSubcommandProcessor}.");
            out.println(" */");
            out.println("public final class GeneratedSubcommandClasses {");
            out.println();
            out.println("    private GeneratedSubcommandClasses() {}");
            out.println();

            // Generate subcommand names set
            out.println("    private static final Set<String> SUBCOMMAND_NAMES;");
            out.println("    static {");
            out.println("        Set<String> names = new LinkedHashSet<>();");
            for (SubcommandEntry entry : entries) {
                out.println("        names.add(\"" + entry.name + "\");");
            }
            out.println("        SUBCOMMAND_NAMES = Collections.unmodifiableSet(names);");
            out.println("    }");
            out.println();

            // Generate class map
            out.println("    private static final Map<String, Class<? extends SignSubcommand>> SUBCOMMAND_CLASSES;");
            out.println("    static {");
            out.println("        Map<String, Class<? extends SignSubcommand>> classes = new LinkedHashMap<>();");
            for (SubcommandEntry entry : entries) {
                out.println("        classes.put(\"" + entry.name + "\", " + entry.qualifiedName + ".class);");
            }
            out.println("        SUBCOMMAND_CLASSES = Collections.unmodifiableMap(classes);");
            out.println("    }");
            out.println();

            // Generate line selector support map
            out.println("    private static final Map<String, Boolean> SUPPORTS_LINE_SELECTOR;");
            out.println("    static {");
            out.println("        Map<String, Boolean> support = new HashMap<>();");
            for (SubcommandEntry entry : entries) {
                out.println("        support.put(\"" + entry.name + "\", " + entry.supportsLineSelector + ");");
            }
            out.println("        SUPPORTS_LINE_SELECTOR = Collections.unmodifiableMap(support);");
            out.println("    }");
            out.println();

            // Generate accessor methods
            out.println("    /**");
            out.println("     * Returns the set of all subcommand names, in registration order.");
            out.println("     */");
            out.println("    public static Set<String> getSubcommandNames() {");
            out.println("        return SUBCOMMAND_NAMES;");
            out.println("    }");
            out.println();

            out.println("    /**");
            out.println("     * Returns the map of subcommand names to their implementation classes.");
            out.println("     */");
            out.println("    public static Map<String, Class<? extends SignSubcommand>> getSubcommandClasses() {");
            out.println("        return SUBCOMMAND_CLASSES;");
            out.println("    }");
            out.println();

            out.println("    /**");
            out.println("     * Returns the subcommand class for the given name, or null if not found.");
            out.println("     */");
            out.println("    public static Class<? extends SignSubcommand> getSubcommandClass(String name) {");
            out.println("        return SUBCOMMAND_CLASSES.get(name);");
            out.println("    }");
            out.println();

            out.println("    /**");
            out.println("     * Returns whether the named subcommand supports line selection.");
            out.println("     */");
            out.println("    public static boolean supportsLineSelector(String name) {");
            out.println("        Boolean supports = SUPPORTS_LINE_SELECTOR.get(name);");
            out.println("        return supports != null && supports;");
            out.println("    }");
            out.println();

            out.println("    /**");
            out.println("     * Returns true if a subcommand with the given name exists.");
            out.println("     */");
            out.println("    public static boolean hasSubcommand(String name) {");
            out.println("        return SUBCOMMAND_NAMES.contains(name);");
            out.println("    }");
            out.println("}");
        }
    }

    private static class SubcommandEntry {
        final String name;
        final String qualifiedName;
        final String simpleName;
        final boolean supportsLineSelector;

        SubcommandEntry(String name, String qualifiedName, String simpleName, boolean supportsLineSelector) {
            this.name = name;
            this.qualifiedName = qualifiedName;
            this.simpleName = simpleName;
            this.supportsLineSelector = supportsLineSelector;
        }
    }
}