/*
 * Copyright (C) 2017-2024 Deltik <https://www.deltik.net/>
 *
 * This file is part of SignEdit for Bukkit.
 *
 * SignEdit for Bukkit is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SignEdit for Bukkit is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SignEdit for Bukkit.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.deltik.mc.signedit;

import net.deltik.mc.signedit.commands.SignCommand;
import net.deltik.mc.signedit.commands.SignCommandTabCompleter;
import net.deltik.mc.signedit.listeners.SignEditListener;
import org.bukkit.command.PluginCommand;
import org.bukkit.event.HandlerList;
import org.bukkit.plugin.java.JavaPlugin;

import javax.inject.Inject;
import javax.inject.Provider;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Set;

public class SignEditPlugin extends JavaPlugin {
    @Inject
    public Configuration config;
    @Inject
    public ConfigurationWatcher configWatcher;
    @Inject
    UserComms userComms;

    @Inject
    public Provider<Set<SignEditListener>> listenersProvider;

    @Inject
    public SignCommand signCommand;
    @Inject
    public SignCommandTabCompleter signCommandTabCompleter;

    @Override
    public void onEnable() {
        DaggerSignEditPluginComponent.builder().plugin(this).build().injectSignEditPlugin(this);

        for (String alias : new String[]{"sign", "signedit", "editsign", "se"}) {
            PluginCommand pluginCommand = this.getCommand(alias);
            pluginCommand.setExecutor(signCommand);
            pluginCommand.setTabCompleter(signCommandTabCompleter);
        }

        reregisterListeners();

        try {
            userComms.deploy();
        } catch (IOException e) {
            getLogger().warning("Cannot enable user-defined locales due to error:");
            getLogger().warning(getStackTrace(e));
        }

        configWatcher.start();
    }

    @Override
    public void onDisable() {
        try {
            configWatcher.end();
            config.configHighstate();
        } catch (IOException e) {
            getLogger().severe(getStackTrace(e));
            throw new IllegalStateException("Unrecoverable error while sanity checking plugin configuration");
        }
    }

    public void reregisterListeners() {
        HandlerList.unregisterAll(this);

        Set<SignEditListener> listeners = listenersProvider.get();
        for (SignEditListener listener : listeners) {
            getServer().getPluginManager().registerEvents(listener, this);
        }
    }

    /**
     * Returns the stack trace of the given {@link Throwable} as a {@link String}
     *
     * @param throwable the {@link Throwable} to be examined
     * @return the stack trace as generated by {@link Throwable#printStackTrace(PrintWriter)}
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }
}
